#!/usr/bin/bash

/usr/bin/time -v trimmomatic PE -threads 8 /home/jjacobso/bgmp/bioinformatics/Bi623/Assignments/QAA/15_R1.fastq /home/jjacobso/bgmp/bioinformatics/Bi623/Assignments/QAA/15_R2.fastq \
15_R1_001_trimmo.fastq.gz 15_R1_001_untrimmo.fastq.gz \
15_R2_001_trimmo.fastq.gz 15_R2_001_untrimmo.fastq.gz \
LEADING:3 TRAILING:3 SLIDINGWINDOW:5:15 MINLEN:35


/usr/bin/time -v trimmomatic PE -threads 8 /home/jjacobso/bgmp/bioinformatics/Bi623/Assignments/QAA/24_R1.fastq /home/jjacobso/bgmp/bioinformatics/Bi623/Assignments/QAA/24_R2.fastq \
24_R1_001_trimmo.fastq.gz 24_R1_001_untrimmo.fastq.gz \
24_R2_001_trimmo.fastq.gz 24_R2_001_untrimmo.fastq.gz \
LEADING:3 TRAILING:3 SLIDINGWINDOW:5:15 MINLEN:35

